"""
Database Seeder for High-Impact Indian Patents (IP India / InPASS).
Populates the Module 5 PostgreSQL 'patents' table with representative Indian patent filings
across AI, Medical Imaging AI, Quantum Computing, Clean Energy, Edge AI, and Cybersecurity.
Assignees include IIT Bombay, IIT Madras, IISc, CSIR, ISRO, DRDO, C-DAC, and Indian Deep-Tech companies.
"""

from datetime import date
import uuid
from sqlalchemy.orm import Session
from sqlalchemy import select

from backend.app.database.connection import SessionLocal
from backend.app.models.patent import Patent

INDIAN_PATENTS_SEED = [
    # Medical Imaging AI
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202311019283",
        "publication_number": "IN202311019283A",
        "title": "Deep Learning System and Method for Automated Detection of Diabetic Retinopathy and Macular Edema in Low-Resource Retinal Fundus Images",
        "abstract": "An artificial intelligence-driven medical imaging framework optimized for edge inference and clinical triage of diabetic retinopathy from low-resolution fundus images captured via handheld ocular devices.",
        "assignee": "Indian Institute of Technology Madras",
        "inventors": "Dr. Mohanasankar Sivaprakasam, Dr. Arun K. Rajagopal",
        "filing_date": date(2023, 3, 15),
        "publication_date": date(2023, 9, 22),
        "classification": "G16H 50/20, G06N 3/08, A61B 3/14",
        "technology_domain": "Medical Imaging AI",
        "citation_count": 8,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202221045981",
        "publication_number": "IN202221045981A",
        "title": "Computer-Aided Diagnostic System for Pulmonary Nodule Segmentation and Malignancy Classification in Low-Dose CT Scans Using Attention CNNs",
        "abstract": "A 3D convolutional neural network architecture with volumetric spatial attention mechanisms for early detection of lung cancer lesions in chest CT scans.",
        "assignee": "Indian Institute of Technology Bombay",
        "inventors": "Dr. Amit Sethi, Priya Ramanathan",
        "filing_date": date(2022, 8, 10),
        "publication_date": date(2023, 2, 18),
        "classification": "G06T 7/00, A61B 6/03, G16H 30/40",
        "technology_domain": "Medical Imaging AI",
        "citation_count": 14,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN398124B",
        "publication_number": "IN398124B",
        "title": "Automated Histopathology Slide Analysis Apparatus Utilizing Multi-Scale Deep Feature Representation for Breast Cancer Grading",
        "abstract": "Apparatus and computerized methodology for gigapixel whole-slide imaging analysis, tumor bed segmentation, and Nottingham histological score calculation.",
        "assignee": "Council of Scientific and Industrial Research (CSIR)",
        "inventors": "Dr. Shantanu Sengupta, Vikram Verma",
        "filing_date": date(2020, 11, 4),
        "publication_date": date(2022, 6, 30),
        "classification": "G01N 33/48, G06V 20/69",
        "technology_domain": "Medical Imaging AI",
        "citation_count": 22,
        "status": "Granted Patent",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Quantum Computing
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202341062019",
        "publication_number": "IN202341062019A",
        "title": "Fault-Tolerant Quantum Error Correction Architecture Using Topological Surface Codes in Superconducting Transmon Qubits",
        "abstract": "A scalable multi-qubit lattice control method for fault-tolerant syndrome measurements with reduced cross-talk in cryogenic quantum processors.",
        "assignee": "Indian Institute of Science (IISc) Bangalore",
        "inventors": "Dr. Vibhor Singh, Balaji Narayanan",
        "filing_date": date(2023, 9, 14),
        "publication_date": date(2024, 3, 29),
        "classification": "G06N 10/70, H01L 39/22",
        "technology_domain": "Quantum Computing",
        "citation_count": 5,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202211078120",
        "publication_number": "IN202211078120A",
        "title": "Quantum Key Distribution Protocol and Photonic Transmitter for Satellite-to-Ground Free-Space Optical Cryptographic Channels",
        "abstract": "Entanglement-based quantum key generation system incorporating adaptive beam steering and atmospheric turbulence compensation for secure satellite communications.",
        "assignee": "Space Applications Centre (ISRO)",
        "inventors": "Dr. R. Umamaheswaran, Neha Deshmukh",
        "filing_date": date(2022, 12, 5),
        "publication_date": date(2023, 6, 16),
        "classification": "H04L 9/08, B64G 1/10",
        "technology_domain": "Quantum Computing",
        "citation_count": 19,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Clean Energy
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN401928B",
        "publication_number": "IN401928B",
        "title": "Solid-State Sodium-Ion Battery Cell with High-Voltage NASICON Cathode and Polymer-Ceramic Composite Electrolyte",
        "abstract": "High energy density sodium-ion electrochemical storage device operating across wide temperature ranges for grid-scale renewable integration and electric mobility.",
        "assignee": "International Advanced Research Centre for Powder Metallurgy and New Materials (ARCI)",
        "inventors": "Dr. R. Gopalan, M. B. Sahana",
        "filing_date": date(2021, 5, 20),
        "publication_date": date(2022, 11, 15),
        "classification": "H01M 10/054, H01M 4/58",
        "technology_domain": "Clean Energy",
        "citation_count": 31,
        "status": "Granted Patent",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202321034901",
        "publication_number": "IN202321034901A",
        "title": "Anion Exchange Membrane Water Electrolyzer with Non-Precious Transition Metal Catalyst for Cost-Effective Green Hydrogen Generation",
        "abstract": "Electrocatalytic water splitting stack utilizing nickel-iron phosphide catalysts on nickel foam substrates for scalable industrial green hydrogen production.",
        "assignee": "National Chemical Laboratory (CSIR-NCL)",
        "inventors": "Dr. Sreekumar Kurungot, Anirban Roy",
        "filing_date": date(2023, 5, 18),
        "publication_date": date(2023, 11, 24),
        "classification": "C25B 1/04, C25B 11/04",
        "technology_domain": "Clean Energy",
        "citation_count": 11,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Edge AI
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202341050119",
        "publication_number": "IN202341050119A",
        "title": "Low-Power Neuromorphic Edge Computing Accelerator with On-Chip Spiking Neural Network Processing for IoT Sensory Nodes",
        "abstract": "Ultra-low power ASIC hardware architecture employing memristive crossbar arrays for asynchronous event-based neuromorphic processing on battery-operated edge devices.",
        "assignee": "Indian Institute of Technology Delhi",
        "inventors": "Dr. Manan Suri, Aditya Bagla",
        "filing_date": date(2023, 7, 25),
        "publication_date": date(2024, 2, 2),
        "classification": "G06N 3/063, G06F 15/78",
        "technology_domain": "Edge AI",
        "citation_count": 7,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Cybersecurity
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202211039822",
        "publication_number": "IN202211039822A",
        "title": "Post-Quantum Cryptographic Key Encapsulation Mechanism and Secure Hardware Module for Critical Infrastructure Protection",
        "abstract": "Lattice-based cryptographic engine resistant to Shor and Grover quantum algorithms, implementing constant-time modular arithmetic for cyber defense.",
        "assignee": "Centre for Development of Advanced Computing (C-DAC)",
        "inventors": "Sanjay Wandhekar, Deepa Taneja",
        "filing_date": date(2022, 7, 12),
        "publication_date": date(2023, 1, 20),
        "classification": "H04L 9/00, G06F 21/72",
        "technology_domain": "Cybersecurity",
        "citation_count": 16,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Synthetic Biology
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202311054219",
        "publication_number": "IN202311054219A",
        "title": "Engineered Microbial Host and Metabolic Pathway for High-Yield Biosynthesis of 2,3-Butanediol from Lignocellulosic Hydrolysate",
        "abstract": "Synthetic biology and metabolic engineering of bacterial strains incorporating CRISPR-Cas9 genome editing for programmable bio-manufacturing of industrial chemicals.",
        "assignee": "International Centre for Genetic Engineering and Biotechnology (ICGEB) New Delhi",
        "inventors": "Dr. Syed Shams Yazdani, Naseem Mansoori",
        "filing_date": date(2023, 8, 11),
        "publication_date": date(2024, 2, 16),
        "classification": "C12N 1/21, C12P 7/18, C12N 15/52",
        "technology_domain": "Synthetic Biology",
        "citation_count": 12,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202241029810",
        "publication_number": "IN202241029810A",
        "title": "Synthetic Genetic Circuits for Programmable Biosensing of Heavy Metals and Pathogen Toxins in Aqueous Media",
        "abstract": "Cell-free synthetic biology expression cassette comprising modular transcriptional repressor gates for ultra-sensitive environmental contaminant diagnostics.",
        "assignee": "Indian Institute of Technology Madras",
        "inventors": "Dr. Karthik Raman, Ananthi Rajendran",
        "filing_date": date(2022, 5, 24),
        "publication_date": date(2022, 12, 2),
        "classification": "C12Q 1/689, C12N 15/63",
        "technology_domain": "Synthetic Biology",
        "citation_count": 9,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN412890B",
        "publication_number": "IN412890B",
        "title": "Engineered Cyanobacterial Strains for Photosynthetic Carbon Dioxide Capture and High-Value Astaxanthin Overproduction",
        "abstract": "Synthetic genomics approach for metabolic flux redirection in engineered microalgae to enhance carbon sequestration and nutraceutical synthesis.",
        "assignee": "Council of Scientific and Industrial Research (CSIR-CFTRI)",
        "inventors": "Dr. R. Sarada, K. S. M. S. Raghavarao",
        "filing_date": date(2021, 3, 19),
        "publication_date": date(2022, 9, 28),
        "classification": "C12N 1/12, C12P 23/00",
        "technology_domain": "Synthetic Biology",
        "citation_count": 21,
        "status": "Granted Patent",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Space Tech
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202341071204",
        "publication_number": "IN202341071204A",
        "title": "Miniaturized Electric Propulsion Hall Effect Thruster with Magnetic Shielding for Low Earth Orbit CubeSats and SmallSat Constellations",
        "abstract": "Sub-kilowatt plasma propulsion system for satellite orbit maintenance, orbital station-keeping, and collision avoidance in miniaturized satellite platforms.",
        "assignee": "Liquid Propulsion Systems Centre (ISRO)",
        "inventors": "Dr. V. Narayanan, K. S. Biju",
        "filing_date": date(2023, 10, 18),
        "publication_date": date(2024, 4, 19),
        "classification": "B64G 1/40, H05H 1/54",
        "technology_domain": "Space Tech",
        "citation_count": 15,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202241060931",
        "publication_number": "IN202241060931A",
        "title": "Additively Manufactured Semi-Cryogenic Rocket Engine Injector Head and Regenerative Cooling Jacket for Reusable Launch Vehicles",
        "abstract": "Monolithic nickel-superalloy coaxial swirl injector matrix fabricated using selective laser melting for throttling reusable rocket propulsion stages.",
        "assignee": "Vikram Sarabhai Space Centre (ISRO)",
        "inventors": "Dr. S. Somanath, S. Unnikrishnan Nair",
        "filing_date": date(2022, 10, 26),
        "publication_date": date(2023, 5, 5),
        "classification": "F02K 9/60, B33Y 80/00, B64G 1/00",
        "technology_domain": "Space Tech",
        "citation_count": 27,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202311048912",
        "publication_number": "IN202311048912A",
        "title": "Autonomous In-Orbit Docking Mechanism and Proximity Operations Guidance System for Satellite Servicing and Space Debris Remediation",
        "abstract": "Computer vision and electromagnetic latching interface enabling non-cooperative target capture, active debris removal, and in-space assembly.",
        "assignee": "Indian Institute of Technology Kanpur",
        "inventors": "Dr. Dipak Kumar Giri, Shubhankar Roy",
        "filing_date": date(2023, 7, 14),
        "publication_date": date(2024, 1, 19),
        "classification": "B64G 1/64, G05D 1/00",
        "technology_domain": "Space Tech",
        "citation_count": 8,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Brain-Computer Interfaces
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202311038192",
        "publication_number": "IN202311038192A",
        "title": "Non-Invasive EEG-Based Brain-Computer Interface System with Real-Time Neural Decoding for Neuroprosthetic Limb Control",
        "abstract": "An adaptive spatial filter and Riemannian geometry manifold decoding framework for continuous motor imagery translation into multi-axis robotic prosthesis commands.",
        "assignee": "Indian Institute of Technology Delhi",
        "inventors": "Dr. Tapan K. Gandhi, Anubha Gupta",
        "filing_date": date(2023, 6, 2),
        "publication_date": date(2023, 12, 8),
        "classification": "A61B 5/372, G06F 3/01, A61F 2/72",
        "technology_domain": "Brain-Computer Interfaces",
        "citation_count": 11,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202221051209",
        "publication_number": "IN202221051209A",
        "title": "Implantable High-Density Neural Microelectrode Array with Wireless Neuromodulation and Bidirectional Neural Signal Acquisition",
        "abstract": "Biocompatible flexible polyimide microelectrode array with on-chip low-noise analog front-end for neural spike recording and closed-loop stimulation.",
        "assignee": "Indian Institute of Technology Bombay",
        "inventors": "Dr. Maryam Shojaei Baghini, Rahul Kulkarni",
        "filing_date": date(2022, 9, 8),
        "publication_date": date(2023, 3, 17),
        "classification": "A61N 1/05, A61B 5/00, H04B 13/00",
        "technology_domain": "Brain-Computer Interfaces",
        "citation_count": 18,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Smart Materials
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202341065112",
        "publication_number": "IN202341065112A",
        "title": "Stimuli-Responsive Self-Healing Polymer Nanocomposite with Reversible Diels-Alder Covalent Network for Structural Aerospace Coatings",
        "abstract": "Thermally and optically triggered autonomous crack-healing elastomeric coating incorporating functionalized graphene oxide for corrosion prevention in high-stress environments.",
        "assignee": "Indian Institute of Science (IISc) Bangalore",
        "inventors": "Dr. Suryasarathi Bose, Prathiksha Pai",
        "filing_date": date(2023, 9, 28),
        "publication_date": date(2024, 3, 29),
        "classification": "C08L 79/08, C09D 5/08, C08K 3/04",
        "technology_domain": "Smart Materials",
        "citation_count": 14,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN405812B",
        "publication_number": "IN405812B",
        "title": "Lead-Free Piezoelectric and Magnetostrictive Multiferroic Composite for Acoustic Energy Harvesting and Intelligent Sensing",
        "abstract": "High-coupling coefficient ceramic-polymer flexible sensor membrane converting ambient vibrational and electromagnetic energy into electrical power.",
        "assignee": "Defence Metallurgical Research Laboratory (DRDO-DMRL)",
        "inventors": "Dr. G. Markandeyulu, V. Subramanian",
        "filing_date": date(2021, 8, 14),
        "publication_date": date(2023, 2, 24),
        "classification": "H01L 41/187, H02N 2/18",
        "technology_domain": "Smart Materials",
        "citation_count": 25,
        "status": "Granted Patent",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Robotics
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202311029011",
        "publication_number": "IN202311029011A",
        "title": "Collaborative Robotic Manipulator with Compliant Actuation and Deep Reinforcement Learning for Adaptive Industrial Assembly",
        "abstract": "Direct force-controlled robotic arm incorporating variable stiffness elastic actuators and safe human-robot collaboration algorithms.",
        "assignee": "Indian Institute of Technology Roorkee",
        "inventors": "Dr. Pushparaj Mani Pathak, Rohit Gupta",
        "filing_date": date(2023, 4, 21),
        "publication_date": date(2023, 10, 27),
        "classification": "B25J 9/16, B25J 13/08",
        "technology_domain": "Robotics",
        "citation_count": 10,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Advanced Battery Technology
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202341041920",
        "publication_number": "IN202341041920A",
        "title": "Silicon-Carbon Composite Anode Material with Conductive Graphene Scaffolding for Fast-Charging High-Capacity Lithium-Ion Batteries",
        "abstract": "Three-dimensional porous silicon-carbon nanostructure mitigating volumetric expansion during rapid lithium intercalation for electric vehicle battery packs.",
        "assignee": "Indian Institute of Technology Hyderabad",
        "inventors": "Dr. Surendra K. Martha, Chhail Bihari Soni",
        "filing_date": date(2023, 6, 20),
        "publication_date": date(2023, 12, 22),
        "classification": "H01M 4/38, H01M 4/587, H01M 10/0525",
        "technology_domain": "Advanced Battery Technology",
        "citation_count": 16,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # Autonomous Vehicles
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202241058912",
        "publication_number": "IN202241058912A",
        "title": "Multi-Sensor Fusion Perception Architecture for Autonomous Navigation in Unstructured Road Environments Using 4D Imaging Radar and LiDAR",
        "abstract": "Real-time probabilistic sensor fusion framework with transformer-based 3D bounding box estimation designed for complex Indian traffic conditions.",
        "assignee": "Tata Motors Limited & IIT Madras",
        "inventors": "Dr. C. S. Shankar Ram, Sandeep Dharmadhikari",
        "filing_date": date(2022, 10, 14),
        "publication_date": date(2023, 4, 21),
        "classification": "G05D 1/02, G01S 13/86, G06V 20/56",
        "technology_domain": "Autonomous Vehicles",
        "citation_count": 19,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
    # 3D Printing / Additive Manufacturing
    {
        "source": "Indian Patent Office (IP India)",
        "source_id": "IN202321049102",
        "publication_number": "IN202321049102A",
        "title": "In-Situ Optical Emission Spectroscopy and Closed-Loop Defect Correction System for Directed Energy Deposition Metal 3D Printing",
        "abstract": "Real-time melt-pool temperature and plasma plume monitoring system with laser power adjustment for porosity-free additive manufacturing of aerospace components.",
        "assignee": "Indian Institute of Technology Bombay",
        "inventors": "Dr. Ramesh Singh, Abhinav Kashyap",
        "filing_date": date(2023, 7, 19),
        "publication_date": date(2024, 1, 26),
        "classification": "B22F 10/25, B33Y 50/02, G01N 21/68",
        "technology_domain": "3D Printing",
        "citation_count": 7,
        "status": "Published Application",
        "official_link": "https://ipindiaservices.gov.in/publicsearch",
    },
]


def seed_indian_patents():
    db: Session = SessionLocal()
    inserted = 0
    skipped = 0
    try:
        for pdata in INDIAN_PATENTS_SEED:
            existing = db.scalar(
                select(Patent).where(
                    Patent.source == pdata["source"],
                    Patent.source_id == pdata["source_id"],
                )
            )
            if existing:
                skipped += 1
                continue

            patent = Patent(
                id=uuid.uuid4(),
                source=pdata["source"],
                source_id=pdata["source_id"],
                publication_number=pdata["publication_number"],
                title=pdata["title"],
                abstract=pdata["abstract"],
                assignee=pdata["assignee"],
                inventors=pdata["inventors"],
                filing_date=pdata["filing_date"],
                publication_date=pdata["publication_date"],
                classification=pdata["classification"],
                technology_domain=pdata["technology_domain"],
                citation_count=pdata["citation_count"],
                status=pdata["status"],
                official_link=pdata["official_link"],
            )
            db.add(patent)
            inserted += 1

        db.commit()
        print(f"Indian Patents Seeding Completed: {inserted} inserted, {skipped} skipped.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding Indian patents: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_indian_patents()
