from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from backend.app.schemas.report import ReportRequest


REPORT_TYPE_NAMES = {
    "funding": "Funding Intelligence Report",
    "patent": "Patent Intelligence Report",
    "research_trend": "Research Trend Report",
    "innovation_intelligence": "Innovation Intelligence Report",
    "commercialization": "Commercialization Report",
}


def _safe_text(value: Any) -> str:
    if value is None:
        return ""

    return str(value)


def _footer(canvas, doc):
    canvas.saveState()

    width, height = A4

    canvas.setFont("Helvetica", 8)

    canvas.drawString(
        20 * mm,
        12 * mm,
        "Research Funding & Innovation Intelligence Platform",
    )

    canvas.drawRightString(
        width - 20 * mm,
        12 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


def generate_pdf_report(
    report: ReportRequest,
) -> bytes:
    """
    Generate a professional PDF from structured report data.

    This service performs presentation/formatting only.
    It does not recalculate innovation, funding, patent, or
    research metrics.
    """

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=report.title,
        author=report.generated_by or "Research Intelligence Platform",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=25,
        spaceAfter=12,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=11,
        leading=15,
        spaceAfter=8,
    )

    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontSize=9.5,
        leading=14,
        spaceAfter=7,
    )

    small_style = ParagraphStyle(
        "ReportSmall",
        parent=styles["Normal"],
        fontSize=8.5,
        leading=11,
    )

    story = []

    report_type_name = REPORT_TYPE_NAMES.get(
        report.report_type,
        report.report_type.replace("_", " ").title(),
    )

    generated_at = (
        report.generated_at
        or datetime.utcnow()
    )

    # ---------------------------------------------------------
    # Cover / Title
    # ---------------------------------------------------------

    story.append(Spacer(1, 25 * mm))

    story.append(
        Paragraph(
            _safe_text(report.title),
            title_style,
        )
    )

    story.append(
        Paragraph(
            _safe_text(report_type_name),
            subtitle_style,
        )
    )

    story.append(Spacer(1, 10 * mm))

    metadata = [
        ["Generated Date", generated_at.strftime("%Y-%m-%d %H:%M UTC")],
    ]

    if report.generated_by:
        metadata.append(
            ["Generated By", report.generated_by]
        )

    if report.organization:
        metadata.append(
            ["Organization", report.organization]
        )

    metadata_table = Table(
        metadata,
        colWidths=[45 * mm, 115 * mm],
    )

    metadata_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story.append(metadata_table)

    story.append(PageBreak())

    # ---------------------------------------------------------
    # Executive Summary
    # ---------------------------------------------------------

    if report.executive_summary:
        story.append(
            Paragraph(
                "Executive Summary",
                heading_style,
            )
        )

        story.append(
            Paragraph(
                _safe_text(report.executive_summary),
                body_style,
            )
        )

    # ---------------------------------------------------------
    # Filters
    # ---------------------------------------------------------

    if report.filters:
        story.append(
            Paragraph(
                "Report Filters",
                heading_style,
            )
        )

        filter_rows = [
            ["Filter", "Value"]
        ]

        for key, value in report.filters.items():
            filter_rows.append(
                [
                    key.replace("_", " ").title(),
                    _safe_text(value),
                ]
            )

        filter_table = Table(
            filter_rows,
            colWidths=[60 * mm, 100 * mm],
            repeatRows=1,
        )

        filter_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )

        story.append(filter_table)

    # ---------------------------------------------------------
    # Report Sections
    # ---------------------------------------------------------

    for section in report.sections:
        story.append(
            Paragraph(
                _safe_text(section.title),
                heading_style,
            )
        )

        for paragraph in section.paragraphs:
            story.append(
                Paragraph(
                    _safe_text(paragraph),
                    body_style,
                )
            )

        if section.table_headers:
            table_data = [
                [
                    Paragraph(
                        _safe_text(header),
                        small_style,
                    )
                    for header in section.table_headers
                ]
            ]

            for row in section.table_rows:
                table_data.append(
                    [
                        Paragraph(
                            _safe_text(cell),
                            small_style,
                        )
                        for cell in row
                    ]
                )

            number_of_columns = len(
                section.table_headers
            )

            available_width = 174 * mm

            if number_of_columns > 0:
                column_width = (
                    available_width / number_of_columns
                )

                column_widths = [
                    column_width
                ] * number_of_columns
            else:
                column_widths = None

            report_table = Table(
                table_data,
                colWidths=column_widths,
                repeatRows=1,
            )

            report_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.lightgrey,
                        ),
                        (
                            "FONTNAME",
                            (0, 0),
                            (-1, 0),
                            "Helvetica-Bold",
                        ),
                        (
                            "GRID",
                            (0, 0),
                            (-1, -1),
                            0.4,
                            colors.grey,
                        ),
                        (
                            "VALIGN",
                            (0, 0),
                            (-1, -1),
                            "TOP",
                        ),
                        (
                            "LEFTPADDING",
                            (0, 0),
                            (-1, -1),
                            4,
                        ),
                        (
                            "RIGHTPADDING",
                            (0, 0),
                            (-1, -1),
                            4,
                        ),
                        (
                            "TOPPADDING",
                            (0, 0),
                            (-1, -1),
                            4,
                        ),
                        (
                            "BOTTOMPADDING",
                            (0, 0),
                            (-1, -1),
                            4,
                        ),
                    ]
                )
            )

            story.append(
                KeepTogether(report_table)
            )

            story.append(Spacer(1, 5 * mm))

    # ---------------------------------------------------------
    # Recommendations
    # ---------------------------------------------------------

    if report.recommendations:
        story.append(
            Paragraph(
                "Recommendations",
                heading_style,
            )
        )

        for index, recommendation in enumerate(
            report.recommendations,
            start=1,
        ):
            story.append(
                Paragraph(
                    f"{index}. {_safe_text(recommendation)}",
                    body_style,
                )
            )

    # ---------------------------------------------------------
    # Build PDF
    # ---------------------------------------------------------

    document.build(
        story,
        onFirstPage=_footer,
        onLaterPages=_footer,
    )

    return buffer.getvalue()