"""add patents table

Revision ID: 15136814ff82
Revises: db08328b87b8
Create Date: 2026-08-27 21:03:10.199812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15136814ff82'
down_revision: Union[str, Sequence[str], None] = 'db08328b87b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_profile_id', sa.UUID(), nullable=False),
    sa.Column('patent_title', sa.Text(), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=True),
    sa.Column('inventor', sa.Text(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('patent_status', sa.String(length=100), nullable=True),
    sa.Column('patent_domain', sa.String(length=150), nullable=True),
    sa.Column('patent_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_research_profile_id'), 'patents', ['research_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patents_research_profile_id'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
