"""Add technologies table

Revision ID: 173c520bc8e5
Revises: 9c8524081965
Create Date: 2026-09-16 20:31:59.052544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173c520bc8e5'
down_revision: Union[str, Sequence[str], None] = '9c8524081965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technology_domain', sa.String(length=255), nullable=True),
    sa.Column('research_paper_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('patent_count', sa.Integer(), nullable=False),
    sa.Column('funding_opportunity_count', sa.Integer(), nullable=False),
    sa.Column('research_growth_rate', sa.Float(), nullable=False),
    sa.Column('patent_growth_rate', sa.Float(), nullable=False),
    sa.Column('funding_growth_rate', sa.Float(), nullable=False),
    sa.Column('emerging_score', sa.Float(), nullable=True),
    sa.Column('emerging_status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology_name', name='uq_technologies_technology_name')
    )
    op.create_index(op.f('ix_technologies_emerging_status'), 'technologies', ['emerging_status'], unique=False)
    op.create_index(op.f('ix_technologies_technology_domain'), 'technologies', ['technology_domain'], unique=False)
    op.create_index(op.f('ix_technologies_technology_name'), 'technologies', ['technology_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technologies_technology_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_technology_domain'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_emerging_status'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
