"""add keywords and profile relationships

Revision ID: 45b603d654e1
Revises: 9e8e3f91812d
Create Date: 2026-08-27 20:51:01.667499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b603d654e1'
down_revision: Union[str, Sequence[str], None] = '9e8e3f91812d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_name'), 'keywords', ['name'], unique=True)
    op.create_table('profile_keywords',
    sa.Column('research_profile_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_profile_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_keywords')
    op.drop_index(op.f('ix_keywords_name'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
