"""add technology activity table

Revision ID: 759f79f4a065
Revises: 173c520bc8e5
Create Date: 2026-09-18 19:52:56.123840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759f79f4a065'
down_revision: Union[str, Sequence[str], None] = '173c520bc8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('research_paper_count', sa.Integer(), nullable=False),
    sa.Column('patent_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('organization_count', sa.Integer(), nullable=False),
    sa.Column('application_diversity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology_id', 'year', name='uq_technology_activity_technology_year')
    )
    op.create_index(op.f('ix_technology_activity_technology_id'), 'technology_activity', ['technology_id'], unique=False)
    op.create_index(op.f('ix_technology_activity_year'), 'technology_activity', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_activity_year'), table_name='technology_activity')
    op.drop_index(op.f('ix_technology_activity_technology_id'), table_name='technology_activity')
    op.drop_table('technology_activity')
    # ### end Alembic commands ###
