"""Add patent intelligence table

Revision ID: 9c8524081965
Revises: ff85a095e06e
Create Date: 2026-09-10 20:10:04.824268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8524081965'
down_revision: Union[str, Sequence[str], None] = 'ff85a095e06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patents', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('patents', sa.Column('source_id', sa.String(length=255), nullable=False))
    op.add_column('patents', sa.Column('publication_number', sa.String(length=100), nullable=False))
    op.add_column('patents', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('patents', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('patents', sa.Column('assignee', sa.Text(), nullable=True))
    op.add_column('patents', sa.Column('inventors', sa.Text(), nullable=True))
    op.add_column('patents', sa.Column('classification', sa.Text(), nullable=True))
    op.add_column('patents', sa.Column('technology_domain', sa.String(length=255), nullable=True))
    op.add_column('patents', sa.Column('citation_count', sa.Integer(), nullable=False))
    op.add_column('patents', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('patents', sa.Column('official_link', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_patents_research_profile_id'), table_name='patents')
    op.create_index(op.f('ix_patents_assignee'), 'patents', ['assignee'], unique=False)
    op.create_index(op.f('ix_patents_filing_date'), 'patents', ['filing_date'], unique=False)
    op.create_index(op.f('ix_patents_publication_date'), 'patents', ['publication_date'], unique=False)
    op.create_index(op.f('ix_patents_publication_number'), 'patents', ['publication_number'], unique=False)
    op.create_index(op.f('ix_patents_source'), 'patents', ['source'], unique=False)
    op.create_index(op.f('ix_patents_status'), 'patents', ['status'], unique=False)
    op.create_index(op.f('ix_patents_technology_domain'), 'patents', ['technology_domain'], unique=False)
    op.create_unique_constraint('uq_patents_source_source_id', 'patents', ['source', 'source_id'])
    op.drop_constraint(op.f('patents_research_profile_id_fkey'), 'patents', type_='foreignkey')
    op.drop_column('patents', 'patent_title')
    op.drop_column('patents', 'patent_number')
    op.drop_column('patents', 'research_profile_id')
    op.drop_column('patents', 'patent_status')
    op.drop_column('patents', 'patent_link')
    op.drop_column('patents', 'patent_domain')
    op.drop_column('patents', 'inventor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patents', sa.Column('inventor', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('patents', sa.Column('patent_domain', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('patents', sa.Column('patent_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patents', sa.Column('patent_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patents', sa.Column('research_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('patents', sa.Column('patent_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patents', sa.Column('patent_title', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('patents_research_profile_id_fkey'), 'patents', 'research_profiles', ['research_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_patents_source_source_id', 'patents', type_='unique')
    op.drop_index(op.f('ix_patents_technology_domain'), table_name='patents')
    op.drop_index(op.f('ix_patents_status'), table_name='patents')
    op.drop_index(op.f('ix_patents_source'), table_name='patents')
    op.drop_index(op.f('ix_patents_publication_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_publication_date'), table_name='patents')
    op.drop_index(op.f('ix_patents_filing_date'), table_name='patents')
    op.drop_index(op.f('ix_patents_assignee'), table_name='patents')
    op.create_index(op.f('ix_patents_research_profile_id'), 'patents', ['research_profile_id'], unique=False)
    op.drop_column('patents', 'official_link')
    op.drop_column('patents', 'status')
    op.drop_column('patents', 'citation_count')
    op.drop_column('patents', 'technology_domain')
    op.drop_column('patents', 'classification')
    op.drop_column('patents', 'inventors')
    op.drop_column('patents', 'assignee')
    op.drop_column('patents', 'abstract')
    op.drop_column('patents', 'title')
    op.drop_column('patents', 'publication_number')
    op.drop_column('patents', 'source_id')
    op.drop_column('patents', 'source')
    # ### end Alembic commands ###
