"""add research areas and profile relationships

Revision ID: 9e8e3f91812d
Revises: b5ecdecaec87
Create Date: 2026-08-27 20:46:34.622436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8e3f91812d'
down_revision: Union[str, Sequence[str], None] = 'b5ecdecaec87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_areas_name'), 'research_areas', ['name'], unique=True)
    op.create_table('profile_research_areas',
    sa.Column('research_profile_id', sa.UUID(), nullable=False),
    sa.Column('research_area_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['research_area_id'], ['research_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_profile_id', 'research_area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_research_areas')
    op.drop_index(op.f('ix_research_areas_name'), table_name='research_areas')
    op.drop_table('research_areas')
    # ### end Alembic commands ###
