"""add research papers table

Revision ID: aa01dc431e9c
Revises: 15136814ff82
Create Date: 2026-09-06 16:51:46.114895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa01dc431e9c'
down_revision: Union[str, Sequence[str], None] = '15136814ff82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal_or_conference', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('research_domain', sa.String(length=150), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('publication_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_research_papers_source_source_id')
    )
    op.create_index(op.f('ix_research_papers_doi'), 'research_papers', ['doi'], unique=False)
    op.create_index(op.f('ix_research_papers_publication_year'), 'research_papers', ['publication_year'], unique=False)
    op.create_index(op.f('ix_research_papers_research_domain'), 'research_papers', ['research_domain'], unique=False)
    op.create_index(op.f('ix_research_papers_source'), 'research_papers', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_papers_source'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_research_domain'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_publication_year'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_doi'), table_name='research_papers')
    op.drop_table('research_papers')
    # ### end Alembic commands ###
