"""add technology areas and profile relationships

Revision ID: aa39f52ae0ad
Revises: 45b603d654e1
Create Date: 2026-08-27 20:55:06.881032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa39f52ae0ad'
down_revision: Union[str, Sequence[str], None] = '45b603d654e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_areas_name'), 'technology_areas', ['name'], unique=True)
    op.create_table('profile_technology_areas',
    sa.Column('research_profile_id', sa.UUID(), nullable=False),
    sa.Column('technology_area_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_area_id'], ['technology_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_profile_id', 'technology_area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_technology_areas')
    op.drop_index(op.f('ix_technology_areas_name'), table_name='technology_areas')
    op.drop_table('technology_areas')
    # ### end Alembic commands ###
