"""add publications table

Revision ID: db08328b87b8
Revises: aa39f52ae0ad
Create Date: 2026-08-27 20:59:54.481240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db08328b87b8'
down_revision: Union[str, Sequence[str], None] = 'aa39f52ae0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('journal_or_conference', sa.String(length=255), nullable=True),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('research_domain', sa.String(length=150), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('publication_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_research_profile_id'), 'publications', ['research_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_research_profile_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
