"""add funding opportunities table

Revision ID: ff85a095e06e
Revises: aa01dc431e9c
Create Date: 2026-09-06 19:07:14.954330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff85a095e06e'
down_revision: Union[str, Sequence[str], None] = 'aa01dc431e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('opportunity_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('funding_type', sa.String(length=100), nullable=True),
    sa.Column('funding_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('funding_category', sa.Text(), nullable=True),
    sa.Column('research_area', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('official_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_funding_opportunities_source_source_id')
    )
    op.create_index(op.f('ix_funding_opportunities_agency'), 'funding_opportunities', ['agency'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_close_date'), 'funding_opportunities', ['close_date'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_open_date'), 'funding_opportunities', ['open_date'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_opportunity_number'), 'funding_opportunities', ['opportunity_number'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_research_area'), 'funding_opportunities', ['research_area'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_source'), 'funding_opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_status'), 'funding_opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_opportunities_status'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_source'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_research_area'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_opportunity_number'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_open_date'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_close_date'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_agency'), table_name='funding_opportunities')
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
