import { useContext, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { AuthContext } from '../context/auth-context'
import { addTechnologyArea, getTechnologyAreas, removeTechnologyArea } from '../services/technologyAreaService'

const profileFields = [['Name', 'name'], ['Email', 'email'], ['Organization', 'organization'], ['Designation', 'designation'], ['Country', 'country'], ['Research domain', 'research_domain']]

function TechnologyAreas({ token }) {
  const [areas, setAreas] = useState([]); const [newArea, setNewArea] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [removingId, setRemovingId] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { let active = true; getTechnologyAreas(token).then(data => { if (active) setAreas(data) }).catch(err => { if (active) setError(err.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [token])
  async function handleAdd(event) { event.preventDefault(); const name = newArea.trim().replace(/\s+/g, ' '); setError(''); setNotice(''); if (name.length < 2) { setError('Enter a technology area using at least 2 characters.'); return } setSubmitting(true); try { const area = await addTechnologyArea(token, name); setAreas(current => [...current, area].sort((a, b) => a.name.localeCompare(b.name))); setNewArea(''); setNotice(`${area.name} added to your technology profile.`) } catch (err) { setError(err.message) } finally { setSubmitting(false) } }
  async function handleRemove(area) { setError(''); setNotice(''); setRemovingId(area.id); try { await removeTechnologyArea(token, area.id); setAreas(current => current.filter(item => item.id !== area.id)); setNotice(`${area.name} removed from your technology profile.`) } catch (err) { setError(err.message) } finally { setRemovingId(null) } }
  return <section className="technology-panel dashboard-technology" aria-labelledby="technology-heading"><div className="panel-heading"><div><p className="eyebrow">TECHNOLOGY AREAS</p><h2 id="technology-heading">Tools behind your research</h2></div><span className="area-count">{areas.length} {areas.length === 1 ? 'area' : 'areas'}</span></div><p className="panel-copy">Add the methods, software, and platforms that are central to your work.</p><form className="technology-add" onSubmit={handleAdd}><label className="sr-only" htmlFor="technology-area">Technology area</label><input id="technology-area" value={newArea} maxLength="100" onChange={event => setNewArea(event.target.value)} placeholder="e.g. Python, TensorFlow, Medical Imaging" disabled={loading || submitting} /><button className="secondary-button" disabled={loading || submitting}>{submitting ? 'Adding...' : 'Add area'}</button></form>{error && <p className="error" role="alert">{error}</p>}{notice && <p className="success" role="status">{notice}</p>}{loading ? <div className="technology-skeleton" aria-label="Loading technology areas"><span /><span /><span /></div> : areas.length > 0 ? <ul className="technology-list">{areas.map(area => <li key={area.id}><span>{area.name}</span><button type="button" onClick={() => handleRemove(area)} disabled={removingId === area.id} aria-label={`Remove ${area.name}`}>{removingId === area.id ? '...' : 'x'}</button></li>)}</ul> : <div className="technology-empty"><span aria-hidden="true">+</span><p>No technology areas yet. Add the tools that shape your research.</p></div>}</section>
}

function ReferenceCard({ title, fields, description }) { return <section className="reference-card"><div><p className="eyebrow">RESEARCH RECORD</p><h2>{title}</h2></div><p>{description}</p><dl>{fields.map(field => <div key={field}><dt>{field}</dt><dd>Not added</dd></div>)}</dl></section> }

export default function Dashboard() {
  const { user, token } = useContext(AuthContext)
  if (user?.role !== 'researcher') return <section className="dashboard account-dashboard"><p className="eyebrow">ACCOUNT DASHBOARD</p><h1>Welcome back, {user?.name}</h1><p className="dashboard-lead">Manage your account details and access the platform features available for your role.</p><div className="profile-grid"><article><span>Name</span><strong>{user?.name}</strong></article><article><span>Email</span><strong>{user?.email}</strong></article><article><span>Account role</span><strong>{user?.role?.replaceAll('_', ' ')}</strong></article></div><Link to="/profile" className="account-dashboard-link">Update account</Link></section>
  return <div className="module-dashboard"><section className="dashboard-intro"><div><p className="eyebrow">RESEARCH PROFILE</p><h1>Welcome back, {user?.name}</h1><p>Your research profile is the foundation for future funding, technology, and innovation intelligence.</p></div><Link to="/profile" className="dashboard-edit-link">Update profile</Link></section><section className="dashboard-section"><div className="section-title"><div><p className="eyebrow">PROFILE AT A GLANCE</p><h2>Researcher details</h2></div><Link to="/profile">Edit details</Link></div><div className="profile-grid dashboard-profile-grid">{profileFields.map(([label, key]) => <article key={key}><span>{label}</span><strong>{user?.[key] || 'Not provided'}</strong></article>)}</div></section><section className="dashboard-section research-signals"><div className="section-title"><div><p className="eyebrow">RESEARCH SIGNALS</p><h2>Research focus</h2></div></div><div className="signal-grid">{[['Research areas', 'Specific fields within your primary domain'], ['Research interests', 'Topics you actively explore'], ['Research keywords', 'Terms that describe your work']].map(([label, copy]) => <article key={label}><span>{label}</span><strong>Not added</strong><p>{copy}</p></article>)}</div></section><TechnologyAreas token={token} /><div className="record-grid"><ReferenceCard title="Publications" description="Your publication record will support research trend and publication analytics." fields={['Title', 'Authors', 'Publication date', 'Journal or conference', 'Publication type', 'Research domain', 'Keywords', 'DOI or publication link']} /><ReferenceCard title="Patents" description="Your patent record will feed future patent analysis and innovation scoring." fields={['Patent title', 'Patent number', 'Inventor', 'Filing date', 'Publication date', 'Patent status', 'Patent domain', 'Patent link']} /></div></div>
}
